### ISSUE TITLE
org.xml.sax.SAXException property onlyupdate is not found on object type liquibase.change.core.LoadUpdatedatachange

### ISSUE THREAD

**Issue by radhikapremier** [liquibase/liquibase-teradata#3]
Hi Team,

we are trying to deploy some Teradata tables into our local using liquibase. We are getting an error in source code of the concerned SDK. Is it a bug ? or we missing something ?
appreciate help on this. Below is the command used.
\bin\teradata\liquibase.jar --changeLogFile=master.changelog.xml --username=XXXXX --password=XXXXX --url="jdbc:teradata://xxxxx/DATABASE=XXXXX" --driver=com.teradata.jdbc.TeraDriver --classpath="C:\bin\teradata\liquibase-teradata-3.1.jar;C:\bin\teradata\tdgssconfig.jar;C:\bin\teradata\terajdbc4.jar" --contexts=DEV --logLevel=info update

Below is the sample log:
Caused by: org.xml.sax.SAXException: Property 'onlyUpdate' not found on object type liquibase.change.core.LoadUpdateDataChange
java.lang.RuntimeException: Property 'onlyUpdate' not found on object type liquibase.change.core.LoadUpdateDataChange
        at liquibase.parser.core.xml.XMLChangeLogSAXHandler.startElement(XMLChangeLogSAXHandler.java:466)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at liquibase.parser.core.xml.XMLChangeLogSAXParser.parse(XMLChangeLogSAXParser.java:98)
        ... 35 more
Caused by: java.lang.RuntimeException: Property 'onlyUpdate' not found on object type liquibase.change.core.LoadUpdateDataChange
        at liquibase.util.ObjectUtil.setProperty(ObjectUtil.java:64)
        at liquibase.parser.core.xml.XMLChangeLogSAXHandler.setProperty(XMLChangeLogSAXHandler.java:521)
        at liquibase.parser.core.xml.XMLChangeLogSAXHandler.startElement(XMLChangeLogSAXHandler.java:350)
        ... 48 more

Thanks in Advance,
Radhika

**Comment by radhikapremier** [comment]
INFO 12/12/18 8:56 AM:liquibase: Successfully acquired change log lock
INFO 12/12/18 8:56 AM:liquibase: Reading from xxxx_TEST.DATABASECHANGELOG
INFO 12/12/18 8:56 AM:liquibase: Reading from xxxx_TEST.DATABASECHANGELOG
INFO 12/12/18 8:56 AM:liquibase: Successfully released change log lock
Liquibase Update Failed: liquibase.database.AbstractJdbcDatabase
SEVERE 12/12/18 8:56 AM:liquibase: liquibase.database.AbstractJdbcDatabase
java.lang.NoClassDefFoundError: liquibase/database/AbstractJdbcDatabase
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at liquibase.ext.teradata.sqlgenerator.CreateTableGeneratorTeradata.supports(CreateTableGeneratorTeradata.java:39)
        at liquibase.ext.teradata.sqlgenerator.CreateTableGeneratorTeradata.supports(CreateTableGeneratorTeradata.java:30)
        at liquibase.sqlgenerator.SqlGeneratorFactory.checkType(SqlGeneratorFactory.java:120)
        at liquibase.sqlgenerator.SqlGeneratorFactory.getGenerators(SqlGeneratorFactory.java:90)
        at liquibase.sqlgenerator.SqlGeneratorFactory.supports(SqlGeneratorFactory.java:155)
        at liquibase.change.AbstractChange.warn(AbstractChange.java:79)
        at liquibase.changelog.visitor.ValidatingVisitor.visit(ValidatingVisitor.java:77)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:58)
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:131)
        at liquibase.Liquibase.update(Liquibase.java:110)
        at liquibase.integration.commandline.Main.doMigration(Main.java:684)
        at liquibase.integration.commandline.Main.main(Main.java:116)
Caused by: java.lang.ClassNotFoundException: liquibase.database.AbstractJdbcDatabase
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 24 more

**Comment by radhikapremier** [comment]
Will the liquibase read the xml code for teradata or it should be in sql blocks?

**Comment by r2datical** [comment]
Can we get an update on this issue? Are you still seeing this behavior? Thanks!

**Comment by r2datical** [comment]
Closing for now. Please reopen if this is still an issue
