### ISSUE TITLE
Exception while executing liquibase update on Teradata

### ISSUE THREAD

**Issue by Ayush4586** [liquibase/liquibase-teradata#58]
Getting below exception when trying to run the jar created by using maven-shade plugin. In Intellij the liquibase update operation executes fine when i run my main class.

using 4.2.1 in maven pom.xml for both core and teradata extension.

Using below line of code to instantiate liquibase:
Database database = DatabaseFactory.getInstance().findCorrectDatabaseImplementation(new JdbcConnection(conn));
Liquibase liquibase = new Liquibase(changeLogPath, new ClassLoaderResourceAccessor(), new JdbcConnection(conn));

the first line throws below exception

Exception : Cannot find generators for database class liquibase.ext.teradata.database.TeradataDatabase, statement: SELECT DATABASE
java.lang.IllegalStateException: Cannot find generators for database class liquibase.ext.teradata.database.TeradataDatabase, statement: SELECT DATABASE
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:218)
	at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:105)
	at liquibase.executor.jvm.JdbcExecutor.access$600(JdbcExecutor.java:40)
	at liquibase.executor.jvm.JdbcExecutor$QueryStatementCallback.doInStatement(JdbcExecutor.java:454)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82)
	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:168)
	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:176)
	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:184)
	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:199)
	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:194)
	at liquibase.ext.teradata.database.TeradataDatabase.getDatabaseName(TeradataDatabase.java:42)
	at liquibase.ext.teradata.database.TeradataDatabase.getDefaultCatalogName(TeradataDatabase.java:106)
	at liquibase.changelog.ChangeLogParameters.<init>(ChangeLogParameters.java:60)
	at liquibase.Liquibase.<init>(Liquibase.java:123)

**Comment by Ayush4586** [comment]
i am using below dependencies in pom:
        <dependency>
            <groupId>com.teradata</groupId>
            <artifactId>tdgssconfig</artifactId>
            <version>16.10</version>
        </dependency>
        <dependency>
            <groupId>com.teradata</groupId>
            <artifactId>terajdbc4</artifactId>
            <version>16.10</version>
        </dependency>

        <dependency>
            <groupId>org.liquibase.ext</groupId>
            <artifactId>liquibase-teradata</artifactId>
            <version>4.3.5</version>
        </dependency>
        
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
            <version>4.3.5</version>
        </dependency>

        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-maven-plugin</artifactId>
            <version>4.3.5</version>
        </dependency>
